import type { Metadata, Viewport } from "next";
import { Roboto } from "next/font/google";
import Favicon from "@/public/icon/icon.ico";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "VisitPurworejo",
  icons: [{ rel: "icon", url: Favicon.src }],
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="mytheme">
      <body
        className={`${roboto.className} base-100`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
