import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Favicon from "@/public/icon/icon.ico"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VisitPurworejo",
  icons: [{ rel: 'icon', url: Favicon.src }],
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className='base-100'>{children}</body>
    </html>
  );
}
