import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Favicon from "@/public/icon/icon.ico"
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "VisitPurworejo",
  icons: [{ rel: 'icon', url: Favicon.src }],
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className={`${roboto.className} base-100`}>{children}</body>
    </html>
  );
}
